export class CategoryVM {
  name: string
  img: string
  // score?: number;
  constructor(name: string, img: string) {
    this.name = name
    this.img = img
  }
}

export const CATEGORIES: CategoryVM[] = [
  new CategoryVM('Dairy and Egg Products', 'dairy1.svg'), // 0
  new CategoryVM('Spices and Herbs', 'spices1.svg'), // 1
  new CategoryVM('Baby Foods', 'baby-food1.svg'), // 2
  new CategoryVM('Fats and Oils', 'oil1.svg'), // 3
  new CategoryVM('Poultry Products', 'poultry1.svg'), // 4
  new CategoryVM('Soups, Sauces, and Gravies', 'soup1.svg'), // 5
  new CategoryVM('Sausages and Luncheon Meats', 'sausage1.svg'), // 6
  new CategoryVM('Breakfast Cereals', 'cereal2.svg'), // 7
  new CategoryVM('Snacks', 'snack1.svg'), // 8
  new CategoryVM('Fruits and Fruit Juices', 'fruit1.svg'), // 9
  new CategoryVM('Pork Products', 'pork1.svg'), // 10
  new CategoryVM('Vegetables and Vegetable Products', 'vegies1.svg'), // 11
  new CategoryVM('Nut and Seed Products', 'nuts1.svg'), // 12
  new CategoryVM('Beef Products', 'beef1.svg'), // 13
  new CategoryVM('Beverages', 'beverage1.svg'), // 14
  new CategoryVM('Finfish and Shellfish Products', 'fish1.svg'), // 15
  new CategoryVM('Legumes and Legume Products', 'peanut1.svg'), // 16
  new CategoryVM('Lamb, Veal, and Game Products', 'lamb.svg'), // 17
  new CategoryVM('Baked Products', 'baked3.svg'), // 18
  new CategoryVM('Sweets', 'candy1.svg'), // 19
  new CategoryVM('Cereal Grains and Pasta', 'pasta3.svg'), // 20
  new CategoryVM('Fast Foods', 'fast-food1.svg'), // 21
  new CategoryVM('Meals, Entrees, and Side Dishes', 'entre2.svg'), // 22
  new CategoryVM('American Indian/Alaska Native Foods', 'igloo.svg'), // 23
  new CategoryVM('Restaurant Foods', 'chef.svg') // 24
]

// DISTANT: (content) move into content
/**
 * @see {@link https://www.allrecipes.com/recipes/?internalSource=hub%20nav&referringId=79&referringContentType=Recipe%20Hub&referringPosition=1&linkName=hub%20nav%20exposed&clickId=hub%20nav%202}
 */
export const SEARCH_CATEGORIES = {
  'Meal Type': {
    'Breakfast and Brunch': {
      Pancakes: {},
      'Breakfast Casseroles': {},
      'Breakfast Eggs': {},
      'Breakfast Quiche': {},
      'French Toast': {},
      Waffles: {},
      'Breakfast Bread': {},
      'Crepes and Blintzes': {},
      'Breakfast Cereals': {},
      'Breakfast Cookies': {},
      'Breakfast Drinks': {},
      'Breakfast Bowls': {},
      'Breakfast Meat and Seafood': {},
      'Breakfast Potatoes': {},
      'Healthy Breakfast and Brunch': {},
      'Southern Breakfast and Brunch': {}
    },
    Desserts: {
      'Cake Recipes': {},
      Candy: {},
      'Caramel Desserts': {},
      Cheesecake: {},
      'Chocolate Desserts': {},
      Cookies: {},
      'Crisps and Crumbles': {},
      Cobbler: {},
      Cupcakes: {},
      'Custards and Puddings': {},
      'Dessert Filling Recipes': {},
      'Pie Recipes': {},
      'Frosting and Icing Recipes': {},
      'Frozen Desserts': {},
      'Fruit Desserts': {},
      Mousse: {},
      'Nut Desserts': {},
      'Specialty Desserts': {},
      'Dessert Sauces': {},
      'Healthy Desserts': {}
    },
    Dinners: {
      'Main Dishes': {},
      'Baked and Roasted Chicken': {},
      'Beef Steaks': {},
      'Cooking for Two': {},
      'Sheet Pan Dinners': {},
      'Healthy Main Dishes': {},
      'Main Dish Salads': {},
      Meatloaf: {},
      'Pasta Main Dishes': {},
      'Pork Chops': {},
      'Quick and Easy Dinners for One': {},
      'Side Dishes': {},
      'Spaghetti Dinner': {},
      'Vegetarian Main Dishes': {},
      'Slow Cooker Main Dishes': {}
    },
    Lunch: {
      'Healthy Lunches': {},
      'Bowl Recipes': {},
      Sandwiches: {},
      'Sandwich Wraps and Roll-Ups': {},
      Soup: {},
      'Salad Recipes': {},
      'School Lunch Ideas and Recipes': {},
      'Healthy School Lunch': {}
    }
  },
  Ingredient: {
    Beef: {
      'Beef Meatloaf': {},
      'Ground Beef': {},
      'Beef Stew': {},
      'Beef Main Dishes': {},
      'Beef Chuck': {},
      'Beef Brisket': {},
      'Beef Steaks': {},
      'Beef Short Loin': {},
      'Beef Sirloin': {},
      'Beef Tenderloin': {},
      'Beef Ribs': {},
      'Prime Rib': {},
      'BBQ & Grilled Beef': {},
      'Beef Casserole': {},
      'Beef Chili': {},
      'Beef Pie': {},
      'Beef Salad': {},
      'Beef Sandwiches': {},
      'Beef Soup': {},
      'Beef Stir-Fry': {},
      Hamburgers: {},
      'Beef Appetizers': {},
      'Beef Sausage': {}
    },
    'Beans and Legumes': {
      'Lima Bean Recipes': {},
      'Black Bean Recipes': {},
      'Cannellini Bean Recipes': {},
      'Chickpea Recipes': {},
      'Kidney Bean Recipes': {},
      'Lentil Recipes': {},
      'Pinto Bean Recipes': {},
      'Black-Eyed Pea Recipes': {},
      'Great Northern Bean Recipes': {},
      'White Bean Recipes': {},
      'Soybean and Edamame Recipes': {},
      'Fava Bean Recipes': {}
    },
    'Chicken Recipes': {
      'Healthy Chicken Main Dishes': {},
      'Slow Cooker Chicken Main Dishes': {},
      'Baked and Roasted Chicken': {},
      'Chicken Breasts': {},
      'Chicken Legs': {},
      'Chicken Sausage': {},
      'Chicken Tenders': {},
      'Chicken Thighs': {},
      'Chicken Wings': {},
      'Ground Chicken': {},
      'Whole Chicken': {},
      'Fried Chicken': {},
      'Chicken Salad': {},
      'Chicken Appetizers': {},
      'BBQ & Grilled Chicken': {},
      'Chicken Chili': {},
      'Chicken Main Dishes': {},
      'Chicken Pie': {},
      'Chicken Sandwiches': {},
      'Chicken Soup': {},
      'Chicken Stew': {},
      'Gourmet Chicken Main Dishes': {},
      'Chicken Stir-Fry': {}
    },
    Chocolate: {
      'Chocolate Desserts': {},
      'Chocolate Muffins': {},
      'Chocolate Popcorn': {},
      'Chocolate Sauce and Hot Fudge': {},
      'Chocolate Shakes and Floats': {},
      'Cocoa Powder': {}
    },
    Fruit: {
      'Apple Recipes': {},
      'Apricot Recipes': {},
      'Avocado Recipes': {},
      'Banana Recipes': {},
      'Berry Recipes': {},
      'Cherry Recipes': {},
      'Citrus Recipes': {},
      'Coconut Recipes': {},
      'Dates Recipes': {},
      'Fig Recipes': {},
      'Fruit Desserts': {},
      'Grapes Recipes': {},
      'Kiwi Recipes': {},
      'Mango Recipes': {},
      'Melon Recipes': {},
      'Nectarine Recipes': {},
      'Papaya Recipes': {},
      'Peach Recipes': {},
      'Pear Recipes': {},
      'Persimmon Recipes': {},
      'Pineapple Recipes': {},
      'Plum Recipes': {},
      'Pomegranate Recipes': {},
      'Raisin Recipes': {},
      'Tamarind Recipes': {}
    },
    'Game Meats': {
      'Venison Recipes': {},
      'Elk Recipes': {},
      'Duck Recipes': {},
      'Goose Recipes': {},
      'Buffalo and Bison Recipes': {},
      'Rabbit Recipes': {},
      'Cornish Hens': {},
      'Veal Recipes': {}
    },
    Grains: {
      Barley: {},
      'Brown Rice': {},
      Buckwheat: {},
      Bulgur: {},
      Cornmeal: {},
      Millet: {},
      Oats: {},
      Quinoa: {},
      Spelt: {},
      'Wild Rice': {},
      'Whole Grain Pancakes': {}
    },
    Mushrooms: {
      'Chanterelle Mushrooms': {},
      'Crimini Mushrooms': {},
      'Enoki Mushrooms': {},
      'Morel Mushrooms': {},
      'Oyster Mushrooms': {},
      'Porcini Mushrooms': {},
      'Portobello Mushrooms': {},
      'Shiitake Mushrooms': {},
      'Vegetarian Mushroom Main Dishes': {},
      'Mushroom Quiche': {}
    },
    Pasta: {
      'Pasta by Shape': {},
      'Pasta Main Dishes': {},
      'Homemade Pasta': {},
      Noodles: {},
      'Pasta Appetizers': {},
      'Pasta Desserts': {},
      'Pasta Salad': {},
      'Pasta Sauces': {}
    },
    'Pork Recipes': {
      'Pork Chops': {},
      'Pork Loin': {},
      'Pork Sausage': {},
      'Pork Shoulder': {},
      'Pork Tenderloin': {},
      'Ground Pork': {},
      'Ham Recipes': {},
      'Bacon Recipes': {},
      'Pork Ribs': {},
      'BBQ & Grilled Pork': {},
      'Pork Casserole': {},
      'Pork Chili': {},
      'Pork Main Dishes': {},
      'Pork Meatloaf': {},
      'Pork Pie': {},
      'Pork Sandwiches': {},
      'Pork Soup': {},
      'Pork Stew': {},
      'Pork Stir-Fry': {}
    },
    Potatoes: {
      'Breakfast Potatoes': {},
      'Mashed Potatoes': {},
      'Roasted Potatoes': {},
      'Potato Side Dishes': {},
      'Potato Soup': {},
      'New Potato Recipes': {},
      'Red Potato Recipes': {},
      'White Potato Recipes': {},
      'BBQ & Grilled Potatoes': {}
    },
    Poultry: {
      'Beef Recipes': {},
      'Chicken Recipes': {},
      'Game Meats': {},
      'Goat Recipes': {},
      'Ham Recipes': {},
      'Lamb Recipes': {},
      'Pork Recipes': {},
      'Sausage Recipes': {},
      'Turkey Recipes': {}
    },
    Rice: {
      'Spanish Rice': {},
      'Mexican Rice': {},
      'Rice Pilaf': {},
      'Brown Rice': {},
      'Wild Rice': {},
      'Fried Rice': {},
      'Rice Casserole': {},
      Risotto: {},
      'Beans and Rice': {}
    },
    Salmon: {
      'Salmon Patties': {},
      'Main Dish Salmon': {},
      'Salmon Salad': {},
      'Smoked Salmon': {},
      'BBQ & Grilled Salmon': {}
    },
    Seafood: {
      'Gourmet Seafood Main Dishes': {},
      'BBQ & Grilled Seafood': {},
      'Healthy Seafood Main Dishes': {},
      'Seafood Main Dishes': {},
      'Seafood Appetizers': {},
      'Seafood Pasta Salad': {},
      'Seafood Stew': {},
      'Fish Recipes': {},
      'Shellfish Recipes': {}
    },
    Shrimp: {
      'BBQ & Grilled Shrimp': {},
      'Main Dish Shrimp': {},
      'Shrimp and Grits': {},
      'Shrimp Appetizers': {},
      'Shrimp Dip': {},
      'Shrimp Pasta': {},
      'Shrimp Pasta Salad': {},
      'Shrimp Salad': {},
      'Shrimp Soup': {},
      'Shrimp Stir-Fry': {}
    },
    'Tofu and Tempeh': {
      'Tofu Recipes': {},
      'Tempeh Recipes': {},
      'TVP Recipes': {},
      'Seitan Recipes': {}
    },
    Turkey: {
      'Ground Turkey': {},
      'Turkey Breasts': {},
      'Turkey Brine': {},
      'Turkey Legs': {},
      'Turkey Sausage': {},
      'Whole Turkey': {},
      'Turkey Appetizers': {},
      'Turkey Casserole': {},
      'Turkey Chili': {},
      'Turkey Main Dishes': {},
      'Turkey Meatloaf': {},
      'Turkey Pot Pie': {},
      'Turkey Salad': {},
      'Turkey Soup': {},
      'BBQ & Grilled Turkey': {}
    },
    'Vegetable Recipes': {
      'Asparagus Side Dishes': {},
      'Broccoli Side Dishes': {},
      'Brussels Sprouts Side Dishes': {},
      'Cabbage Side Dishes': {},
      'Carrot Side Dishes': {},
      'Cauliflower Side Dishes': {},
      'Corn Side Dishes': {},
      'Eggplant Side Dishes': {},
      'Green Bean Side Dishes': {},
      'Green Pea Side Dishes': {},
      'Greens Side Dishes': {},
      'Onion Side Dishes': {},
      'Potato Side Dishes': {},
      'Roasted Vegetables': {},
      'Squash Side Dishes': {},
      'Summer Squash Side Dishes': {},
      'Sweet Potato Side Dishes': {},
      'Tomato Side Dishes': {},
      'Zucchini Side Dishes': {}
    }
  },
  'Diet and Health': {
    Diabetic: {},
    'Low Carb Recipes': {},
    'Dairy Free Recipes': {},
    'Gluten Free': {},
    Healthy: {},
    'Heart-Healthy Recipes': {},
    'High Fiber Recipes': {},
    'Low Calorie': {},
    'Low Cholesterol Recipes': {},
    'Low Fat': {},
    'Weight-Loss Recipes': {}
  },
  Seasonal: {
    '4th of July': {
      '4th of July Appetizers': {},
      '4th of July Desserts': {},
      '4th of July Main Dishes': {},
      '4th of July BBQ & Grilling': {},
      '4th of July Salads': {},
      '4th of July Side Dishes': {},
      '4th of July Patriotic Recipes': {}
    },
    'Baby Shower': {
      'Christmas Cookies': {},
      'Christmas Appetizers': {},
      'Christmas Baking': {},
      'Christmas Bread': {},
      'Christmas Breakfast and Brunch': {},
      'Christmas Cakes': {},
      'Christmas Candy': {},
      'Christmas Desserts': {},
      'Christmas Fudge': {},
      'Christmas Main Dishes': {},
      'Christmas Side Dishes': {},
      'Christmas Salads': {},
      'Christmas Drink Recipes': {},
      'Food Gifts': {},
      Eggnog: {},
      'Mulled Wine': {}
    },
    Birthday: {},
    Christmas: {},
    'Christmas Cookies': {
      'Sugar Cookies': {},
      Biscotti: {},
      'Butter Cookies': {},
      'Chocolate Chip Cookies': {},
      'Cookie Icing and Frosting': {},
      'Cut-Out Cookies': {},
      'Gingerbread Cookies': {},
      Gingersnaps: {},
      'International Cookies': {},
      'Lebkuchen Cookies': {},
      'No-Bake Cookies': {},
      'Oatmeal Cookies': {},
      'Peanut Butter Cookies': {},
      'Pfeffernusse Cookies': {},
      'Pizzelle Cookies': {},
      'Shortbread Cookies': {},
      'Springerle Cookies': {},
      'Spritz Cookies': {},
      'Thumbprint Cookies': {}
    },
    'Cinco de Mayo': {
      Guacamole: {},
      Margaritas: {},
      'Mexican Recipes': {},
      'Mexican Desserts': {},
      'Mexican Drinks': {},
      Nachos: {},
      Salsa: {}
    },
    'Easter Recipes': {
      'Easter Appetizers': {},
      'Deviled Eggs': {},
      'Easter Bread': {},
      'Easter Breakfast and Brunch': {},
      'Easter Dinner': {},
      'Easter Ham': {},
      'Easter Lamb': {},
      'Easter Desserts': {},
      'Carrot Cake': {},
      'Easter Salads': {},
      'Easter Side Dishes': {},
      'Potatoes Au Gratin': {},
      'Scalloped Potatoes': {},
      'Easter Leftovers': {}
    },
    Football: {
      'Big Game Appetizers and Snacks': {},
      'Big Game Drinks': {},
      'Big Game Main Dishes': {},
      'Big Game Treats': {}
    },
    Halloween: {
      'Halloween Appetizers and Snacks': {},
      'Halloween Cookies': {},
      'Halloween Cupcakes': {},
      'Halloween Cakes': {},
      'Halloween Drinks': {},
      'Halloween Main Dishes': {},
      'Halloween Treats and Desserts': {},
      'Caramel Apples': {},
      'Leftover Candy Recipes': {},
      'Pumpkin Recipes': {},
      'Pumpkin Seeds': {}
    },
    Hanukkah: {
      'Hanukkah Appetizers': {},
      'Hanukkah Latkes': {},
      'Hanukkah Brisket': {},
      'Hanukkah Cookies': {},
      'Hanukkah Doughnuts': {},
      'Hanukkah Kugel': {}
    },
    'Mothers Day': {
      'Mothers Day Breakfast and Brunch': {},
      'Mothers Day Dinner': {},
      'Mothers Day Desserts': {}
    },
    'New Year': {
      'New Years Appetizers': {},
      'New Years Main Dishes': {},
      'New Years Desserts': {},
      'New Years Drinks With Alcohol': {},
      'New Years Drinks Without Alcohol': {},
      'New Years Breakfast and Brunch': {},
      'New Years Good Luck Foods': {},
      'New Years Side Dishes': {},
      'Greens Recipes': {},
      'New Year, New You': {}
    },
    Passover: {
      'Seder Appetizers': {},
      'Seder Main Dishes': {},
      'Seder Side Dishes': {},
      'Seder Desserts': {},
      'Everyday Passover Meals': {},
      'Seder Recipes': {}
    },
    Ramadan: {
      'Ramadan Main Dishes': {},
      'Ramadan Desserts': {}
    },
    'St. Patricks Day': {
      'St. Patricks Day Appetizers': {},
      'St. Patricks Day Breakfast and…': {},
      'St. Patricks Day Main Dishes': {},
      'St. Patricks Day Side Dishes': {},
      'St. Patricks Day Desserts': {},
      'Corned Beef and Cabbage': {},
      'Irish Stew': {},
      'Irish Soda Bread': {},
      'Irish Recipes': {},
      'Guinness® Recipes': {}
    },
    Thanksgiving: {
      'Thanksgiving Appetizers': {},
      'Thanksgiving Bread': {},
      'Thanksgiving Desserts': {},
      'Thanksgiving Pies': {},
      'Thanksgiving Drinks': {},
      'Thanksgiving Gravy': {},
      'Thanksgiving Main Dishes': {},
      'Thanksgiving Turkey': {},
      'Thanksgiving Side Dishes': {},
      'Thanksgiving Potatoes': {},
      'Thanksgiving Salads': {},
      'Thanksgiving Stuffing and Dressing': {},
      'Thanksgiving Sweet Potatoes': {},
      'Vegetarian Thanksgiving': {},
      'Vegan Thanksgiving': {},
      'Make-Ahead Thanksgiving': {},
      'Healthy Thanksgiving': {},
      'Quick and Easy Thanksgiving': {},
      'Thanksgiving Breakfast': {},
      'Paleo Thanksgiving': {},
      'Gluten-Free Thanksgiving': {},
      'Thanksgiving Leftovers': {},
      'Cranberry Recipes': {}
    },
    'Valentines Day': {
      'Valentines Day Appetizers': {},
      'Valentines Day Breakfast and Brunch': {},
      'Valentines Day Cakes': {},
      'Valentines Day Candy': {},
      'Valentines Day Cookies': {},
      'Valentines Day Cupcakes': {},
      'Valentines Day Desserts': {},
      'Valentines Day Drinks': {},
      'Valentines Day Main Dishes': {},
      'Valentines Day Salads': {},
      'Valentines Day School Treats': {}
    },
    'More Holidays and Events': {
      'Big Game Recipes': {},
      'Lunar New Year Recipes': {},
      'Valentines Day Recipes': {},
      'Mardi Gras Recipes': {},
      'St. Patricks Day Recipes': {},
      'Events and Gatherings': {},
      'Purim Recipes': {},
      'Passover Recipes': {},
      'Easter Recipes': {},
      'Lent Recipes': {},
      'Cinco de Mayo Recipes': {},
      'Mothers Day Recipes': {},
      'Memorial Day Recipes': {},
      'Ramadan Recipes': {},
      'Fathers Day Recipes': {},
      '4th of July Recipes': {},
      'Labor Day Recipes': {},
      'Rosh Hashanah Recipes': {},
      'Back to School Recipes': {},
      'Halloween Recipes': {},
      'Oktoberfest Recipes': {},
      'Tailgating Recipes': {},
      'Veterans Day Recipes': {},
      'Thanksgiving Recipes': {},
      'Hanukkah Recipes': {},
      'Christmas Recipes': {},
      'New Years Recipes': {},
      'Kwanzaa Recipes': {}
    }
  },
  'Dish Type': {
    'Appetizers & Snacks': {
      Antipasto: {},
      'Bacon Appetizers': {},
      Bruschetta: {},
      'Canapes and Crostini': {},
      'Cheese Appetizers': {},
      'Crab Cakes': {},
      Crackers: {},
      'Deviled Eggs': {},
      'Dips and Spreads': {},
      'Jalapeno Poppers': {},
      'Kids Snacks': {},
      'Pasta Appetizers': {},
      'Pastry Appetizers': {},
      'Dill Pickles and Sweet Pickles': {},
      'Meatball Appetizers': {},
      'Mushroom Appetizers': {},
      'Olive Appetizers': {},
      'Party Mix': {},
      'Pickled Eggs': {},
      Popcorn: {},
      'Seafood Appetizers': {},
      'Shrimp Appetizers': {},
      'Slow Cooker Appetizers': {},
      'Snack Recipes': {},
      'Spicy Appetizers': {},
      'Stuffed Mushrooms': {},
      'Tapas Recipes': {},
      'Vegetable Appetizers': {},
      'Wraps and Rolls Appetizers': {},
      'Bean and Pea Appetizers': {},
      'Fruit Appetizers': {},
      'Garlic Bread': {},
      'Meat and Poultry Appetizers': {},
      'Nuts and Seeds Appetizers': {}
    },
    'Bread Recipes': {
      Bagels: {},
      'Banana Bread': {},
      Challah: {},
      'Cranberry Bread': {},
      'Egg Bread': {},
      'Flat Bread': {},
      'Holiday Bread': {},
      'No-Knead Bread Recipes': {},
      'Pizza Dough and Crusts': {},
      'Potato Bread': {},
      Pretzels: {},
      'Pumpkin Bread': {},
      'Quick Bread': {},
      'Roll and Bun Recipes': {},
      'Sourdough Bread': {},
      'White Bread': {},
      'Whole Grain Bread': {},
      'Yeast Bread': {},
      'Zucchini Bread': {},
      'Bread Machine': {},
      Pastries: {},
      Biscuit: {},
      Cornbread: {},
      'Healthy Bread': {}
    },
    'Cake Recipes': {
      'Angel Food Cake': {},
      'Apple Cake': {},
      'Banana Cake': {},
      'Birthday Cake': {},
      'Blueberry Cake': {},
      'Bundt Cake': {},
      'Cake Pop Recipes': {},
      'Carrot Cake': {},
      Cheesecake: {},
      'Chocolate Cake': {},
      'Coconut Cake': {},
      'Coffee Cake': {},
      Cupcakes: {},
      Fruitcake: {},
      'Holiday Cakes': {},
      'Lemon Cake': {},
      'Mug Cake': {},
      'Peach Cake': {},
      'Pineapple Cake': {},
      'Poke Cake': {},
      'Pound Cake': {},
      'Pumpkin Cake': {},
      'Pumpkin Rolls': {},
      'Red Velvet Cake': {},
      'Sheet Cake': {},
      Shortcake: {},
      'Spice Cake': {},
      'Sponge Cake': {},
      'Strawberry Cake': {},
      Tortes: {},
      'Upside-Down Cake': {},
      'Wedding Cakes': {},
      'White Cake': {},
      'Yellow Cake': {},
      'Zucchini Cake': {},
      'Cake Mix Cakes': {},
      'Frosting and Icing Recipes': {}
    },
    'Candy and Fudge': {
      'Candy Brittle': {},
      'Caramel Recipes': {},
      'Chocolate Bark': {},
      'Chocolate Candy': {},
      Divinity: {},
      Fudge: {},
      'Fruit Candy': {},
      'Mint Candy': {},
      'Nut Candy': {},
      'Popcorn Candy': {},
      Toffee: {},
      Truffles: {},
      'Christmas Fudge': {},
      'Homemade Marshmallows': {}
    },
    'Casserole Recipes': {
      'Beef Casserole': {},
      'Chicken Casserole': {},
      'Mexican Casserole': {},
      'Noodle Casserole': {},
      'Pork Casserole': {},
      'Rice Casserole': {},
      'Seafood Casserole': {},
      'Shepherds Pie': {},
      'Tater Tots® Casserole': {},
      'Tuna Casserole': {},
      'Turkey Casserole': {},
      'Vegetable Casserole': {},
      'Vegetarian Main Dish Casseroles': {},
      'Breakfast Casseroles': {},
      'Healthy Casseroles': {},
      'Side Dish Casseroles': {}
    },
    'Christmas Cookies': {
      'Sugar Cookies': {},
      Biscotti: {},
      'Butter Cookies': {},
      'Chocolate Chip Cookies': {},
      'Cookie Icing and Frosting': {},
      'Cut-Out Cookies': {},
      'Gingerbread Cookies': {},
      Gingersnaps: {},
      'International Cookies': {},
      'Lebkuchen Cookies': {},
      'No-Bake Cookies': {},
      'Oatmeal Cookies': {},
      'Peanut Butter Cookies': {},
      'Pfeffernusse Cookies': {},
      'Pizzelle Cookies': {},
      'Shortbread Cookies': {},
      'Springerle Cookies': {},
      'Spritz Cookies': {},
      'Thumbprint Cookies': {}
    },
    'Cocktail Recipes': {
      'Beer Cocktails': {},
      'Blended Cocktails': {},
      'Bloody Marys': {},
      'Bourbon Drinks': {},
      'Champagne Drinks': {},
      Cosmopolitans: {},
      Daiquiris: {},
      Hurricanes: {},
      'Gin Drinks': {},
      Margaritas: {},
      Martinis: {},
      Mojitos: {},
      'Rum Drinks': {},
      'Tequila Drinks': {},
      'Vodka Drinks': {},
      'Whiskey Drinks': {},
      'Drink Flavoring & Simple Syrups': {}
    },
    'Cookie Recipes': {
      'Bar Cookies': {},
      Biscotti: {},
      Brownies: {},
      'Butter Cookies': {},
      'Chocolate Chip Cookies': {},
      'Chocolate Cookies': {},
      'Christmas Cookies': {},
      'Cut-Out Cookies': {},
      'Drop Cookies': {},
      'Filled Cookies': {},
      'Fruit Cookies': {},
      'Gingerbread Cookies': {},
      'Sandwich Cookies': {},
      'Thumbprint Cookies': {},
      Gingersnaps: {},
      'International Cookies': {},
      Macaroons: {},
      'Meringue Cookies': {},
      'Molasses Cookies': {},
      'No-Bake Cookies': {},
      'Nut Cookies': {},
      'Oatmeal Cookies': {},
      'Peanut Butter Cookies': {},
      'Pumpkin Cookies': {},
      'Refrigerator Cookies': {},
      'Shortbread Cookies': {},
      Snickerdoodles: {},
      'Spice Cookies': {},
      'Sugar Cookies': {},
      'Whoopie Pies': {},
      'Zucchini Cookies': {},
      'Cake Mix Cookies': {},
      'Cookie Icing and Frosting': {}
    },
    'Mac and Cheese Recipes': {
      'Baked Macaroni and Cheese': {},
      'Stovetop Macaroni and Cheese': {}
    },
    'Main Dishes': {
      'Beef Main Dishes': {},
      'Beef Stroganoff': {},
      Burgers: {},
      Casseroles: {},
      'Chicken Main Dishes': {},
      Goulash: {},
      Lasagna: {},
      'Macaroni and Cheese': {},
      'Main Dish Salads': {},
      'Main Dish Soups and Stews': {},
      Meatballs: {},
      Meatloaf: {},
      Pizza: {},
      'Pasta Main Dishes': {},
      'Pork Chops': {},
      'Pork Main Dishes': {},
      Quiche: {},
      'Rice Main Dishes': {},
      Sandwiches: {},
      'Stir-Fries': {},
      'Stuffed Bell Peppers': {},
      'Stuffed Main Dishes': {},
      'Seafood Main Dishes': {},
      Tacos: {},
      'Turkey Main Dishes': {},
      'Vegetable Main Dishes': {},
      'Bowl Recipes': {},
      Calzones: {},
      'Curry Main Dishes': {},
      Dumplings: {},
      'Deep Fried Main Dishes': {},
      'Savory Pies': {},
      'Steaks and Chops': {},
      Ribs: {},
      Roasts: {},
      'Gourmet Main Dishes': {},
      'Healthy Main Dishes': {},
      'Quick and Easy Dinners': {},
      'Slow Cooker Main Dishes': {},
      'Vegetarian Main Dishes': {},
      'Vegan Main Dishes': {},
      'Chinese Main Dishes': {},
      'Filipino Main Dishes': {},
      'French Main Dishes': {},
      'Greek Main Dishes': {},
      'Indian Main Dishes': {},
      'Italian Main Dishes': {},
      'Japanese Main Dishes': {},
      'Mexican Main Dishes': {},
      'Thai Main Dishes': {},
      'Southern Main Dishes': {},
      'Fall Main Dishes': {},
      'Summer Main Dishes': {},
      'Spring Main Dishes': {},
      'Winter Main Dishes': {}
    },
    'Pasta Salad Recipes': {
      'Pasta by Shape': {},
      'Pasta Main Dishes': {},
      'Homemade Pasta': {},
      Noodles: {},
      'Pasta Appetizers': {},
      'Pasta Desserts': {},
      'Pasta Salad': {},
      'Pasta Sauces': {}
    },
    'Pasta Recipes': {
      'Pasta by Shape': {},
      'Pasta Main Dishes': {},
      'Homemade Pasta': {},
      Noodles: {},
      'Pasta Appetizers': {},
      'Pasta Desserts': {},
      'Pasta Salad': {},
      'Pasta Sauces': {}
    },
    'Pie Recipes': {
      'Apple Pie': {},
      'Banana Pie': {},
      'Chess Pie': {},
      'Chocolate Pie': {},
      'Coconut Pie': {},
      'Custard and Cream Pies': {},
      'Dessert Tarts': {},
      'Fruit Pies': {},
      'Ice Cream Pie': {},
      'Key Lime Pie': {},
      'Lemon Meringue Pie': {},
      'Mincemeat Pie': {},
      'No-Bake Pies': {},
      'Peanut Butter Pie': {},
      'Pecan Pie': {},
      'Pie Crusts': {},
      'Pumpkin Pie': {},
      'Slab Pie': {},
      'Sweet Potato Pie': {},
      'Thanksgiving Pies': {},
      'Vintage Pies': {}
    },
    Pizza: {
      'Beef Pizza': {},
      'Breakfast Pizza': {},
      Calzones: {},
      'Chicken Pizza': {},
      'Pepperoni Pizza': {},
      'Pizza Dough and Crusts': {},
      'Pizza Sauce': {},
      'Veggie Pizza': {},
      'Kids Pizza Recipes': {}
    },
    Sandwiches: {
      'Bacon Sandwiches': {},
      'Beef Sandwiches': {},
      'Cheese Sandwiches': {},
      'Grilled Cheese Sandwiches': {},
      'Chicken Sandwiches': {},
      'Ham Sandwiches': {},
      'Pork Sandwiches': {},
      'Tuna Sandwiches': {},
      'Turkey Sandwiches': {},
      'Heroes, Hoagies and Subs': {},
      Gyros: {},
      Panini: {},
      'Sandwich Wraps and Roll-Ups': {},
      'Sloppy Joes': {},
      'Hot Dogs and Corn Dogs': {}
    },
    'Sauces and Condiments': {
      'BBQ Sauce': {},
      'Salad Dressings': {},
      Sauces: {},
      Marinades: {},
      'Canning and Preserving': {},
      'Compound Butters': {},
      Croutons: {},
      'Pesto Sauce': {},
      Rubs: {},
      Applesauce: {},
      Chutney: {},
      Gravy: {},
      Relishes: {},
      Syrups: {},
      'Tzatziki Sauce': {}
    },
    'Smoothie Recipes': {
      'Banana Smoothies': {},
      'Blueberry Smoothies': {},
      'Green Smoothies': {},
      'Mango Smoothies': {},
      'Orange Smoothies': {},
      'Strawberry Smoothies': {},
      'Veggie Smoothies': {},
      'Smoothie Bowl Recipes': {}
    },
    'Soups, Stew, and Chili Recipes': {
      Soup: {},
      'Chicken Noodle Soup': {},
      Stew: {},
      Chili: {},
      'Broth and Stocks': {},
      Bisque: {},
      Chowder: {},
      'Healthy Soups and Stews': {},
      'Main Dish Soups and Stews': {}
    }
  },
  'Cooking Style': {
    'BBQ & Grilling': {
      'BBQ &amp; Grilled Appetizers': {},
      'BBQ &amp; Grilled Beef': {},
      'BBQ &amp; Grilled Burgers': {},
      'BBQ &amp; Grilled Chicken': {},
      'BBQ &amp; Grilled Lamb': {},
      'BBQ &amp; Grilled Pork': {},
      'BBQ &amp; Grilled Seafood': {},
      'BBQ &amp; Grilled Skewers and…': {},
      'BBQ &amp; Grilled Turkey': {},
      'BBQ &amp; Grilled Fruit': {},
      'BBQ &amp; Grilled Vegetables': {},
      'BBQ &amp; Grilled Salads': {},
      'BBQ &amp; Grilled Side Dishes': {},
      'BBQ Sauces, Marinades and Rubs': {},
      'Quick and Easy BBQ &amp; Grilling': {},
      'Smoked Foods': {},
      'Vegetarian BBQ &amp; Grilling': {}
    },
    'Budget Cooking': {},
    'Clean-Eating': {
      Smoothies: {},
      'Smoothie Bowl Recipes': {},
      Quinoa: {},
      'Kale Recipes': {},
      'Healthy Breakfast and Brunch': {},
      'Vegan Recipes': {}
    },
    'Cooking for Kids': {
      'Kids Chicken Recipes': {},
      'Kids Pork Recipes': {},
      'Kids Pasta Recipes': {},
      'Kids Beef Recipes': {},
      'Kids Pizza Recipes': {},
      'Kid Chefs': {},
      'Kids Vegetable Recipes': {},
      'Kids Fish Recipes': {},
      'Kids Drink Recipes': {},
      'Healthy Kid Recipes': {},
      'Kids Breakfast': {}
    },
    'Cooking for Two': {
      'Cooking Beef for Two': {},
      'Cooking Pork for Two': {},
      'Cooking Seafood for Two': {},
      'Cooking Chicken for Two': {},
      'Cooking Breakfast for Two': {},
      'Cooking Lunch for Two': {}
    },
    Gourmet: {
      'Gourmet Main Dishes': {},
      'Gourmet Side Dishes': {},
      'Gourmet Desserts': {},
      'Gourmet Appetizers': {},
      'Gourmet Salads': {},
      'Gourmet Bread': {}
    },
    Paleo: {
      'Paleo Breakfast and Brunch': {},
      'Paleo Main Dishes': {},
      'Paleo Side Dishes': {},
      'Paleo Desserts': {},
      'Paleo Salads': {}
    },
    'Pressure Cooker': {
      'Instant Pot® Recipes': {}
    },
    'Quick & Easy': {
      'Quick and Easy Appetizers': {},
      'Quick and Easy Dinners': {},
      'Quick and Easy Side Dishes': {},
      'Quick and Easy Breakfast': {},
      'Quick and Easy Desserts': {},
      '15-Minute Meals': {},
      '30-Minute Meals': {},
      '45-Minute Meals': {}
    },
    'Slow Cooker': {
      'Slow Cooker Main Dishes': {},
      'Slow Cooker Beef Main Dishes': {},
      'Slow Cooker Chicken Main Dishes': {},
      'Slow Cooker Pork Main Dishes': {},
      'Slow Cooker Soup and Stew': {},
      'Vegetarian Slow Cooker Recipes': {},
      'Italian Slow Cooker Recipes': {},
      'Mexican Slow Cooker Recipes': {},
      'Slow Cooker BBQ Recipes': {},
      'Slow Cooker Appetizers': {},
      'Slow Cooker Desserts': {},
      'Slow Cooker Sauces and Condiments': {},
      'Slow Cooker Side Dishes': {},
      'Healthy Slow Cooker Recipes': {}
    },
    Vegan: {
      'Vegan Breakfast and Brunch': {},
      'Vegan Bread': {},
      'Vegan Soups and Stews': {},
      'Vegan Desserts': {},
      'Vegan Main Dishes': {},
      'Vegan Side Dishes': {},
      'Vegan Holiday Recipes': {},
      'Vegan Thanksgiving': {},
      'Vegetarian Recipes': {}
    },
    Vegetarian: {
      'Vegetarian Soups and Stews': {},
      'Vegetarian Chili': {},
      'Vegetarian Lasagna': {},
      'Vegan Recipes': {},
      'Vegetarian Appetizers': {},
      'Vegetarian Breakfast and Brunch': {},
      'Vegetarian Main Dishes': {},
      'Vegetarian Side Dishes': {},
      'Vegetarian Slow Cooker Recipes': {},
      'Vegetarian Pie': {},
      'Vegetarian Quiche': {},
      'Vegetarian BBQ &amp; Grilling': {},
      'Vegetarian Protein': {},
      'Vegetarian Whole Grain': {},
      'Vegetarian Thanksgiving': {},
      'Healthy Vegetarian Main Dishes': {},
      'Quick and Easy Vegetarian Recipes': {},
      'Vegetarian Pasta Salad': {},
      'Vegetarian Pasta Sauce': {}
    }
  },
  'World Cuisine': {
    Chinese: {
      'Chinese Appetizers': {},
      'Chinese Main Dishes': {},
      'Chinese Beef Main Dishes': {},
      'Chinese Chicken Main Dishes': {},
      'Chinese Pork Main Dishes': {},
      'Chinese Seafood Main Dishes': {},
      'Chinese Soups and Stews': {},
      'Stir-Fries': {}
    },
    Indian: {
      'Indian Appetizers': {},
      'Indian Bread': {},
      'Indian Side Dishes': {},
      'Indian Desserts': {},
      'Indian Drinks': {},
      'Indian Main Dishes': {}
    },
    Italian: {
      'Italian Appetizers': {},
      'Italian Bread': {},
      'Italian Desserts': {},
      'Italian Drinks': {},
      'Italian Main Dishes': {},
      'Italian Salads': {},
      'Italian Side Dishes': {},
      'Italian Soups and Stews': {},
      'Authentic Italian Recipes': {},
      Lasagna: {},
      Spaghetti: {},
      Pizza: {},
      Calzones: {}
    },
    Mexican: {
      'Authentic Mexican Recipes': {},
      'Mexican Appetizers': {},
      'Mexican Main Dishes': {},
      'Mexican Drinks': {},
      'Mexican Desserts': {},
      'Mexican Side Dishes': {},
      'Mexican Salads': {},
      'Mexican Bread': {},
      Burritos: {},
      'Chile Rellenos': {},
      Enchiladas: {},
      Fajitas: {},
      'Mexican Tacos': {},
      'Mexican Fish Tacos': {},
      'Mexican Rice': {},
      'Mexican Soups and Stews': {},
      Quesadillas: {}
    },
    Southern: {
      'Southern Desserts': {},
      'Southern Main Dishes': {},
      'Southern Soups and Stews': {},
      'Southern Bread': {},
      'Southern Side Dishes': {},
      'Southern Drinks': {},
      'Southern Breakfast and Brunch': {},
      'Southern Appetizers': {}
    },
    Thai: {
      'Thai Appetizers': {},
      'Thai Main Dishes': {},
      'Pad Thai': {},
      'Thai Soups and Stews': {},
      'Thai Desserts': {}
    },
    'All World Cuisine': {
      'Mexican Recipes': {},
      'Italian Recipes': {},
      'Chinese Recipes': {},
      'Indian Recipes': {},
      'Thai Recipes': {},
      'Asian Recipes': {},
      'Latin American Recipes': {},
      'Middle Eastern Recipes': {},
      'African Recipes': {},
      'European Recipes': {},
      'Australian and New Zealander Recipes': {},
      'Canadian Recipes': {},
      'French Recipes': {},
      'Japanese Recipes': {},
      'Korean Recipes': {},
      'Mediterranean Diet': {},
      'U.S. Recipes': {}
    }
  }
}
